<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Tracer.TestHarness\Tracer.TestHarness.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Aggregator.Cli\Tracer.Aggregator.Cli.csproj" />
    <ProjectReference Include="..\..\src\Tracer.OfflineViewer\Tracer.OfflineViewer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

</Project>
