<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <CycloneDdsDisableCodeGen>true</CycloneDdsDisableCodeGen>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Tracer.Core\Tracer.Core.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Storage.DuckDB\Tracer.Storage.DuckDB.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Storage.DuckDB.MultiInterval\Tracer.Storage.DuckDB.MultiInterval.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Bundle\Tracer.Bundle.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Aggregator\Tracer.Aggregator.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Adapters.Mock\Tracer.Adapters.Mock.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Agent\Tracer.Agent.csproj" />
    <ProjectReference Include="..\..\src\Tracer.WebApi\Tracer.WebApi.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Observer\Tracer.Observer.csproj" />
    <ProjectReference Include="..\..\src\Tracer.TestHarness\Tracer.TestHarness.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Storage.Parquet\Tracer.Storage.Parquet.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Storage.Annotations\Tracer.Storage.Annotations.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Storage.SavedViews\Tracer.Storage.SavedViews.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Storage.SavedQueries\Tracer.Storage.SavedQueries.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Adapters.DDS\Tracer.Adapters.DDS.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Adapters.SharedMemory\Tracer.Adapters.SharedMemory.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Adapters.Sync\Tracer.Adapters.Sync.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Adapters.Nas\Tracer.Adapters.Nas.csproj" />
    <ProjectReference Include="..\..\src\Tracer.AdapterSelection\Tracer.AdapterSelection.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <None Update="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
