<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Tracer.Core\Tracer.Core.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Storage.DuckDB\Tracer.Storage.DuckDB.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Storage.DuckDB.MultiInterval\Tracer.Storage.DuckDB.MultiInterval.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Bundle\Tracer.Bundle.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Aggregator\Tracer.Aggregator.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Adapters.Mock\Tracer.Adapters.Mock.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Agent\Tracer.Agent.csproj" />
    <ProjectReference Include="..\..\src\Tracer.WebApi\Tracer.WebApi.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Observer\Tracer.Observer.csproj" />
    <ProjectReference Include="..\..\src\Tracer.TestHarness\Tracer.TestHarness.csproj" />
    <ProjectReference Include="..\..\src\Tracer.Storage.Parquet\Tracer.Storage.Parquet.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
