<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Tracer.Storage.DuckDB</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Tracer.Tests.Unit</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Tracer.Aggregator</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tracer.Core\Tracer.Core.csproj" />
    <ProjectReference Include="..\Tracer.Bundle\Tracer.Bundle.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DuckDB.NET.Data" />
    <PackageReference Include="DuckDB.NET.Bindings.Full" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Parquet.Net" />
  </ItemGroup>

</Project>
