<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Tracer.Adapters.DDS</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tracer.Core\Tracer.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CycloneDDS.NET" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
