<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Tracer.Bundle</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Tracer.Tests.Unit</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tracer.Core\Tracer.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ulid" />
    <PackageReference Include="System.IO.Compression.ZipFile" />
  </ItemGroup>

</Project>
